version: "3.8"

services:
  insaned:
    container_name: insaned
    build: .
    restart: "always"
    privileged: true
    depends_on:
      - scanservjs
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - SCAN_URL=http://scanservjs:8080/api/v1/scan
      - SCANSERVJS_DEVICE_ID=fujitsu:ScanSnap iX500:1503743
      - SCANSERVJS_PIPELINE=@:pipeline.ocr | PDF (JPG | @:pipeline.high-quality)

  scanservjs:
    image: sbs20/scanservjs:latest
    container_name: scanservjs-container
    privileged: true
    restart: unless-stopped
    environment:
      - OCR_LANG=deu
    ports:
      - "9002:8080"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
